services:
  postgres:
    image: postgres:latest
    container_name: kanji-postgres
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
    volumes:
      - kanji-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kanji_user -d kanji_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - kanji-network

  migrate:
    image: node:18-alpine
    env_file:
      - .env.docker
    networks:
      - kanji-network
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "./scripts/migrate.sh"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    environment:
      - NODE_ENV=production
    depends_on:
      migrate:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    volumes:
      - ./:/app/
    networks:
      - kanji-network

networks:
  kanji-network:
    driver: bridge

volumes:
  kanji-postgres-data:
  node_modules: